import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {stripTypeScriptTypes} from 'node:module';
import {createJiti} from '/home/timmypai/.pi/agent/npm/node_modules/jiti/lib/jiti.mjs';
const jiti=createJiti(import.meta.url);
const path='/home/timmypai/.pi/agent/npm/node_modules/pi-subagents/src/runs/';
const mod=await jiti.import(path+'shared/structured-output.ts');
const source=readFileSync(process.argv[2]??path+'background/subagent-runner.ts','utf8');
const start=source.indexOf('\t\tlet structuredOutput: unknown;');
const end=source.indexOf('\t\tconst errorMessages =',start);
assert.ok(start>=0&&end>start);
const code=stripTypeScriptTypes(source.slice(start,end));
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const collect=new AsyncFunction('run','effectiveStructuredOutput','readStructuredOutput','readStructuredOutputAcceptanceReport','MISSING_STRUCTURED_OUTPUT_CALL_ERROR',`let toolAvailabilityError, midToolExitError, structuredAcceptanceReport, structuredAcceptanceReportError; ${code};return {structuredOutput,structuredError,validatedStructuredOutput};`);
const root=mkdtempSync(join(tmpdir(),'report-regression-'));
try{
 const schema={type:'object',properties:{value:{type:'number'}},required:['value'],additionalProperties:false};
 const runtime={schema,schemaPath:join(root,'schema.json'),outputPath:join(root,'output.json')};
 writeFileSync(runtime.schemaPath,JSON.stringify(schema));writeFileSync(runtime.outputPath,JSON.stringify({value:7}));
 const base={exitCode:0,error:undefined,timedOut:false,stopped:false,structuredOutputToolInvoked:true,messages:[{role:'toolResult',toolName:'structured_output',isError:false}]};
 const run=overrides=>collect({...base,...overrides},runtime,mod.readStructuredOutput,mod.readStructuredOutputAcceptanceReport,mod.MISSING_STRUCTURED_OUTPUT_CALL_ERROR);
 assert.deepEqual(await run({}),{structuredOutput:{value:7},structuredError:undefined,validatedStructuredOutput:true});
 const failed=await run({exitCode:1,error:'WebSocket error'});
 assert.deepEqual(failed.structuredOutput,{value:7});assert.equal(failed.validatedStructuredOutput,false);
 assert.equal((await run({error:'WebSocket error',messages:[]})).structuredOutput,undefined,'no capture evidence: do not return stale file');
 for(const key of ['timedOut','stopped'])assert.equal((await run({[key]:true,error:'failure'})).structuredOutput,undefined);
 writeFileSync(runtime.outputPath,JSON.stringify({value:'invalid'}));
 const invalid=await run({error:'WebSocket error'});assert.equal(invalid.structuredOutput,undefined);assert.ok(invalid.structuredError);
 // Execute the actual error projection; execution failure must survive report retention.
 const errorStart=source.indexOf('\t\tconst error = executionError && structuredOutput');
 const errorEnd=source.indexOf('\t\tconst attempt: ModelAttempt',errorStart);
 assert.ok(errorStart>=0&&errorEnd>errorStart);
 const project=new Function('executionError','structuredOutput','effectiveStructuredOutput',source.slice(errorStart,errorEnd)+'return error;');
 const error=project('WebSocket error',{value:7},runtime);assert.match(error,/WebSocket error/);assert.match(error,/not accepted/);assert.ok(error.includes(runtime.outputPath));
 assert.equal(project(undefined,{value:7},runtime),undefined);
 assert.ok(source.includes('if (capturedReport) break modelAttemptsLoop;'),'captured work cannot be automatically replayed');
 const fg=readFileSync(process.argv[3]??path+'foreground/execution.ts','utf8');
 const fgStart=fg.indexOf('\tlet validatedStructuredOutput = false;');
 const fgEnd=fg.indexOf('\n\tif (result.exitCode === 0 && !result.error) {',fgStart);
 assert.ok(fgStart>=0&&fgEnd>fgStart);
 const fgCollect=new AsyncFunction('result','options','structuredOutputToolInvoked','readStructuredOutput','readStructuredOutputAcceptanceReport','MISSING_STRUCTURED_OUTPUT_CALL_ERROR',stripTypeScriptTypes(fg.slice(fgStart,fgEnd))+';return {result,validatedStructuredOutput};');
 const foreground=overrides=>fgCollect({...base,...overrides},{structuredOutput:runtime},true,mod.readStructuredOutput,mod.readStructuredOutputAcceptanceReport,mod.MISSING_STRUCTURED_OUTPUT_CALL_ERROR);
 const fgInvalid=await foreground({exitCode:1,error:'WebSocket error'});assert.match(fgInvalid.result.error,/WebSocket error/);assert.match(fgInvalid.result.error,/Report validation failed/);
 writeFileSync(runtime.outputPath,JSON.stringify({value:7}));
 const fgFailed=await foreground({exitCode:1,error:'WebSocket error'});assert.deepEqual(fgFailed.result.structuredOutput,{value:7});assert.equal(fgFailed.result.exitCode,1);assert.equal(fgFailed.result.error,'WebSocket error');assert.equal(fgFailed.validatedStructuredOutput,false);
 assert.equal((await foreground({})).validatedStructuredOutput,true);
 for(const key of ['timedOut','stopped'])assert.equal((await foreground({[key]:true,error:'failure'})).result.structuredOutput,undefined);
 assert.equal((await foreground({error:'failure',messages:[]})).result.structuredOutput,undefined);
 console.log('PASS foreground + background actual ingestion blocks and native schema reader: retain failed report/error; no success promotion; no-capture, malformed, stopped/timed-out protections; retry guard present.');
}finally{rmSync(root,{recursive:true,force:true});}
